-- config/pg.sql
create table public.links (
  id bigint generated by default as identity not null,
  link text not null,
  short text not null,
  created_at timestamp with time zone not null default now(),
  clicks integer not null default 0,
  constraint links_pkey primary key (id),
  constraint links_short_key unique (short)
) TABLESPACE pg_default;

CREATE OR REPLACE FUNCTION increment_clicks(short_hash text)
RETURNS void AS $$
  UPDATE public.links
  SET clicks = clicks + 1
  WHERE short = short_hash;
$$ LANGUAGE sql;