create table public.links (
  link text not null,
  short text not null,
  id bigint generated by default as identity not null,
  created_at timestamp with time zone not null default now(),
  constraint links_pkey primary key (id)
) TABLESPACE pg_default;